
package com.aiurt.modules.robot.robotdata.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "ServicePortType", targetNamespace = "http://tempuri.org/robotdata.xsd/Service.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePortType {


    /**
     * Service definition of function robotdata__GetRobotConnect
     * 获取机器人系统连接信息
     * @return
     *     returns com.wgp.ConnectInfos
     */
    @WebMethod(operationName = "GetRobotConnect")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotConnect", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotConnect")
    @ResponseWrapper(localName = "GetRobotConnectResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotConnectResponse")
    public ConnectInfos getRobotConnect();

    /**
     * Service definition of function robotdata__GetRobotInfo
     *
     * @return
     *     returns com.wgp.RobotInfos
     */
    @WebMethod(operationName = "GetRobotInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotInfo", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotInfo")
    @ResponseWrapper(localName = "GetRobotInfoResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotInfoResponse")
    public RobotInfos getRobotInfo();

    /**
     * Service definition of function robotdata__GetRobotTime
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRobotTime")
    @WebResult(name = "RobotTime", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotTime", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotTime")
    @ResponseWrapper(localName = "GetRobotTimeResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotTimeResponse")
    public String getRobotTime();

    /**
     * Service definition of function robotdata__SetRobotTime
     *
     * @param robotTime
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SetRobotTime")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "SetRobotTime", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.SetRobotTime")
    @ResponseWrapper(localName = "SetRobotTimeResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.SetRobotTimeResponse")
    public int setRobotTime(
            @WebParam(name = "RobotTime", targetNamespace = "")
                    String robotTime);

    /**
     * Service definition of function robotdata__SetCurrentRobot
     *
     * @param robotIp
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SetCurrentRobot")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "SetCurrentRobot", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.SetCurrentRobot")
    @ResponseWrapper(localName = "SetCurrentRobotResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.SetCurrentRobotResponse")
    public int setCurrentRobot(
            @WebParam(name = "RobotIp", targetNamespace = "")
                    String robotIp);

    /**
     * Service definition of function robotdata__ReleaseCurrentRobot
     *
     * @param robotIp
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ReleaseCurrentRobot")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "ReleaseCurrentRobot", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.ReleaseCurrentRobot")
    @ResponseWrapper(localName = "ReleaseCurrentRobotResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.ReleaseCurrentRobotResponse")
    public int releaseCurrentRobot(
            @WebParam(name = "RobotIp", targetNamespace = "")
                    String robotIp);

    /**
     * Service definition of function robotdata__SetControlMode
     *
     * @param controlType
     * @param robotIp
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SetControlMode")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "SetControlMode", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.SetControlMode")
    @ResponseWrapper(localName = "SetControlModeResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.SetControlModeResponse")
    public int setControlMode(
            @WebParam(name = "RobotIp", targetNamespace = "")
                    String robotIp,
            @WebParam(name = "ControlType", targetNamespace = "")
                    int controlType);

    /**
     * Service definition of function robotdata__GetControlMode
     *
     * @param robotIp
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetControlMode")
    @WebResult(name = "ControlType", targetNamespace = "")
    @RequestWrapper(localName = "GetControlMode", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetControlMode")
    @ResponseWrapper(localName = "GetControlModeResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetControlModeResponse")
    public int getControlMode(
            @WebParam(name = "RobotIp", targetNamespace = "")
                    String robotIp);

    /**
     * Service definition of function robotdata__RobotSpeedControl
     *
     * @param linearVelocity
     * @param angularVelocity
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotSpeedControl")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotSpeedControl", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotSpeedControl")
    @ResponseWrapper(localName = "RobotSpeedControlResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotSpeedControlResponse")
    public int robotSpeedControl(
            @WebParam(name = "LinearVelocity", targetNamespace = "")
                    double linearVelocity,
            @WebParam(name = "AngularVelocity", targetNamespace = "")
                    double angularVelocity);

    /**
     * Service definition of function robotdata__RobotYuntaiControl
     *
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotYuntaiControl")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotYuntaiControl", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotYuntaiControl")
    @ResponseWrapper(localName = "RobotYuntaiControlResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotYuntaiControlResponse")
    public int robotYuntaiControl(
            @WebParam(name = "Type", targetNamespace = "")
                    YuntaiControlType type);

    /**
     * Service definition of function robotdata__RobotCameraControl
     *
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotCameraControl")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotCameraControl", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotCameraControl")
    @ResponseWrapper(localName = "RobotCameraControlResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotCameraControlResponse")
    public int robotCameraControl(
            @WebParam(name = "Type", targetNamespace = "")
                    CameraControlType type);

    /**
     * Service definition of function robotdata__RobotLightControl
     *
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotLightControl")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotLightControl", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotLightControl")
    @ResponseWrapper(localName = "RobotLightControlResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotLightControlResponse")
    public int robotLightControl(
            @WebParam(name = "Type", targetNamespace = "")
                    LightControlType type);

    /**
     * Service definition of function robotdata__RobotWiperControl
     *
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotWiperControl")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotWiperControl", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotWiperControl")
    @ResponseWrapper(localName = "RobotWiperControlResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotWiperControlResponse")
    public int robotWiperControl(
            @WebParam(name = "Type", targetNamespace = "")
                    WiperControlType type);

    /**
     * Service definition of function robotdata__RobotFlirControl
     *
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotFlirControl")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotFlirControl", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotFlirControl")
    @ResponseWrapper(localName = "RobotFlirControlResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotFlirControlResponse")
    public int robotFlirControl(
            @WebParam(name = "Type", targetNamespace = "")
                    FilrControlType type);

    /**
     * Service definition of function robotdata__RobotLifterControl
     *
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotLifterControl")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotLifterControl", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotLifterControl")
    @ResponseWrapper(localName = "RobotLifterControlResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotLifterControlResponse")
    public int robotLifterControl(
            @WebParam(name = "Type", targetNamespace = "")
                    LifterControlType type);

    /**
     * Service definition of function robotdata__RobotPdControl
     *
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotPdControl")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotPdControl", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotPdControl")
    @ResponseWrapper(localName = "RobotPdControlResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.RobotPdControlResponse")
    public int robotPdControl(
            @WebParam(name = "Type", targetNamespace = "")
                    PdControlType type);

    /**
     * Service definition of function robotdata__GetRobotBatteryInfo
     *
     * @param needAll
     * @return
     *     returns com.wgp.BatteryInfos
     */
    @WebMethod(operationName = "GetRobotBatteryInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotBatteryInfo", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotBatteryInfo")
    @ResponseWrapper(localName = "GetRobotBatteryInfoResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotBatteryInfoResponse")
    public BatteryInfos getRobotBatteryInfo(
            @WebParam(name = "NeedAll", targetNamespace = "")
                    boolean needAll);

    /**
     * Service definition of function robotdata__GetRobotSpeedInfo
     *
     * @param needAll
     * @return
     *     returns com.wgp.SpeedInfos
     */
    @WebMethod(operationName = "GetRobotSpeedInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotSpeedInfo", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotSpeedInfo")
    @ResponseWrapper(localName = "GetRobotSpeedInfoResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotSpeedInfoResponse")
    public SpeedInfos getRobotSpeedInfo(
            @WebParam(name = "NeedAll", targetNamespace = "")
                    boolean needAll);

    /**
     * Service definition of function robotdata__GetRobotTaskState
     *
     * @param needAll
     * @return
     *     returns com.wgp.RobotTaskStates
     */
    @WebMethod(operationName = "GetRobotTaskState")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotTaskState", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotTaskState")
    @ResponseWrapper(localName = "GetRobotTaskStateResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotTaskStateResponse")
    public RobotTaskStates getRobotTaskState(
            @WebParam(name = "NeedAll", targetNamespace = "")
                    boolean needAll);

    /**
     * Service definition of function robotdata__GetRobotPosInfo
     *
     * @param needAll
     * @return
     *     returns com.wgp.RobotPosInfos
     */
    @WebMethod(operationName = "GetRobotPosInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotPosInfo", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotPosInfo")
    @ResponseWrapper(localName = "GetRobotPosInfoResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotPosInfoResponse")
    public RobotPosInfos getRobotPosInfo(
            @WebParam(name = "NeedAll", targetNamespace = "")
                    boolean needAll);

    /**
     * Service definition of function robotdata__GetRobotYunTaiInfo
     *
     * @param needAll
     * @return
     *     returns com.wgp.RobotYunTaiInfos
     */
    @WebMethod(operationName = "GetRobotYunTaiInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotYunTaiInfo", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotYunTaiInfo")
    @ResponseWrapper(localName = "GetRobotYunTaiInfoResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotYunTaiInfoResponse")
    public RobotYunTaiInfos getRobotYunTaiInfo(
            @WebParam(name = "NeedAll", targetNamespace = "")
                    boolean needAll);

    /**
     * Service definition of function robotdata__GetRobotMileageInfo
     *
     * @param needAll
     * @return
     *     returns com.wgp.RobotMileageInfos
     */
    @WebMethod(operationName = "GetRobotMileageInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotMileageInfo", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotMileageInfo")
    @ResponseWrapper(localName = "GetRobotMileageInfoResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotMileageInfoResponse")
    public RobotMileageInfos getRobotMileageInfo(
            @WebParam(name = "NeedAll", targetNamespace = "")
                    boolean needAll);

    /**
     * Service definition of function robotdata__GetRobotGasInfo
     *
     * @param needAll
     * @return
     *     returns com.wgp.RobotGasInfos
     */
    @WebMethod(operationName = "GetRobotGasInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotGasInfo", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotGasInfo")
    @ResponseWrapper(localName = "GetRobotGasInfoResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotGasInfoResponse")
    public RobotGasInfos getRobotGasInfo(
            @WebParam(name = "NeedAll", targetNamespace = "")
                    boolean needAll);

    /**
     * Service definition of function robotdata__GetRobotAlarmInfo
     *
     * @param needAll
     * @return
     *     returns com.wgp.RobotAlarmInfos
     */
    @WebMethod(operationName = "GetRobotAlarmInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotAlarmInfo", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotAlarmInfo")
    @ResponseWrapper(localName = "GetRobotAlarmInfoResponse", targetNamespace = "http://tempuri.org/robotdata.xsd", className = "com.wgp.GetRobotAlarmInfoResponse")
    public RobotAlarmInfos getRobotAlarmInfo(
            @WebParam(name = "NeedAll", targetNamespace = "")
                    boolean needAll);

}
