image: maven:3.6.3-jdk-8

stages:
  - scanner

example-sonar:
  stage: scanner
  tags:
    - gitlab-pos
  script:
    - mvn clean verify -Dmaven.test.skip=true 
    - mvn  --batch-mode sonar:sonar
        -Dsonar.host.url=http://192.168.1.65:9000
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
        -Dsonar.gitlab.project_id=$CI_PROJECT_ID
        -Dsonar.issuesReport.html.enable=true
        -Dsonar.login=d2cefad6207f50a4abca1b30bd264036be334654
        -Dsonar.projectKey=com.aiurt.project:aiurt-platform 
        -Dsonar.projectName=运维管理系统
  only:
    - dev