
package com.aiurt.modules.robot.taskdata.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "ServicePortType", targetNamespace = "http://tempuri.org/taskdata.xsd/Service.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePortType {


    /**
     * Service definition of function taskdata__GetMapAreaInfo
     *
     * @return
     *     returns com.wgptwo.MapAreaInfos
     */
    @WebMethod(operationName = "GetMapAreaInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetMapAreaInfo", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetMapAreaInfo")
    @ResponseWrapper(localName = "GetMapAreaInfoResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetMapAreaInfoResponse")
    public MapAreaInfos getMapAreaInfo();

    /**
     * Service definition of function taskdata__GetPatrolAreaInfo
     *
     * @return
     *     returns com.wgptwo.PatrolAreaInfos
     */
    @WebMethod(operationName = "GetPatrolAreaInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetPatrolAreaInfo", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetPatrolAreaInfo")
    @ResponseWrapper(localName = "GetPatrolAreaInfoResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetPatrolAreaInfoResponse")
    public PatrolAreaInfos getPatrolAreaInfo();

    /**
     * Service definition of function taskdata__GetMapEdgeInfo
     *
     * @param areaId
     * @return
     *     returns com.wgptwo.MapEdgeInfos
     */
    @WebMethod(operationName = "GetMapEdgeInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetMapEdgeInfo", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetMapEdgeInfo")
    @ResponseWrapper(localName = "GetMapEdgeInfoResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetMapEdgeInfoResponse")
    public MapEdgeInfos getMapEdgeInfo(
            @WebParam(name = "AreaId", targetNamespace = "")
                    String areaId);

    /**
     * Service definition of function taskdata__GetDockPointInfo
     *
     * @return
     *     returns com.wgptwo.DockPointInfos
     */
    @WebMethod(operationName = "GetDockPointInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetDockPointInfo", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetDockPointInfo")
    @ResponseWrapper(localName = "GetDockPointInfoResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetDockPointInfoResponse")
    public DockPointInfos getDockPointInfo();

    /**
     * Service definition of function taskdata__GetPatrolPointInfo
     *
     * @return
     *     returns com.wgptwo.PatrolPointInfos
     */
    @WebMethod(operationName = "GetPatrolPointInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetPatrolPointInfo", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetPatrolPointInfo")
    @ResponseWrapper(localName = "GetPatrolPointInfoResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetPatrolPointInfoResponse")
    public PatrolPointInfos getPatrolPointInfo();

    /**
     * Service definition of function taskdata__GetRobotPatrolDockPathInfo
     *
     * @param robotIp
     * @return
     *     returns com.wgptwo.RobotPatrolDockPathInfo
     */
    @WebMethod(operationName = "GetRobotPatrolDockPathInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetRobotPatrolDockPathInfo", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetRobotPatrolDockPathInfo")
    @ResponseWrapper(localName = "GetRobotPatrolDockPathInfoResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetRobotPatrolDockPathInfoResponse")
    public RobotPatrolDockPathInfo getRobotPatrolDockPathInfo(
            @WebParam(name = "robotIp", targetNamespace = "")
                    String robotIp);

    /**
     * Service definition of function taskdata__GetTaskPathInfo
     *
     * @return
     *     returns com.wgptwo.TaskPathInfos
     */
    @WebMethod(operationName = "GetTaskPathInfo")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetTaskPathInfo", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetTaskPathInfo")
    @ResponseWrapper(localName = "GetTaskPathInfoResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetTaskPathInfoResponse")
    public TaskPathInfos getTaskPathInfo();

    /**
     * Service definition of function taskdata__StartTaskByPathId
     *
     * @param taskPathId
     * @return
     *     returns com.wgptwo.TaskInfo
     */
    @WebMethod(operationName = "StartTaskByPathId")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "StartTaskByPathId", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.StartTaskByPathId")
    @ResponseWrapper(localName = "StartTaskByPathIdResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.StartTaskByPathIdResponse")
    public TaskInfo startTaskByPathId(
            @WebParam(name = "TaskPathId", targetNamespace = "")
                    String taskPathId);

    /**
     * Service definition of function taskdata__StartTaskByPointList
     *
     * @param pointList
     * @return
     *     returns com.wgptwo.TaskInfo
     */
    @WebMethod(operationName = "StartTaskByPointList")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "StartTaskByPointList", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.StartTaskByPointList")
    @ResponseWrapper(localName = "StartTaskByPointListResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.StartTaskByPointListResponse")
    public TaskInfo startTaskByPointList(
            @WebParam(name = "PointList", targetNamespace = "")
                    List<String> pointList);

    /**
     * Service definition of function taskdata__SetTaskPathInfo
     *
     * @param info
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SetTaskPathInfo")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "SetTaskPathInfo", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.SetTaskPathInfo")
    @ResponseWrapper(localName = "SetTaskPathInfoResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.SetTaskPathInfoResponse")
    public int setTaskPathInfo(
            @WebParam(name = "info", targetNamespace = "")
                    TaskPathInfo info);

    /**
     * Service definition of function taskdata__StartTaskByIdAndTime
     *
     * @param startTime
     * @param taskPathId
     * @return
     *     returns int
     */
    @WebMethod(operationName = "StartTaskByIdAndTime")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "StartTaskByIdAndTime", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.StartTaskByIdAndTime")
    @ResponseWrapper(localName = "StartTaskByIdAndTimeResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.StartTaskByIdAndTimeResponse")
    public int startTaskByIdAndTime(
            @WebParam(name = "TaskPathId", targetNamespace = "")
                    String taskPathId,
            @WebParam(name = "StartTime", targetNamespace = "")
                    String startTime);

    /**
     * Service definition of function taskdata__RobotControlTask
     *
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "RobotControlTask")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "RobotControlTask", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.RobotControlTask")
    @ResponseWrapper(localName = "RobotControlTaskResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.RobotControlTaskResponse")
    public int robotControlTask(
            @WebParam(name = "Type", targetNamespace = "")
                    ControlTaskType type);

    /**
     * Service definition of function taskdata__GetTaskExcuteData
     *
     * @param robotIp
     * @return
     *     returns com.wgptwo.TaskExcuteData
     */
    @WebMethod(operationName = "GetTaskExcuteData")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetTaskExcuteData", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetTaskExcuteData")
    @ResponseWrapper(localName = "GetTaskExcuteDataResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetTaskExcuteDataResponse")
    public TaskExcuteData getTaskExcuteData(
            @WebParam(name = "robotIp", targetNamespace = "")
                    String robotIp);

    /**
     * Service definition of function taskdata__GetPatrolResult
     *
     * @return
     *     returns com.wgptwo.TaskExcuteInfos
     */
    @WebMethod(operationName = "GetPatrolResult")
    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "GetPatrolResult", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetPatrolResult")
    @ResponseWrapper(localName = "GetPatrolResultResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.GetPatrolResultResponse")
    public TaskExcuteInfos getPatrolResult();

    /**
     * Service definition of function taskdata__TaskPathOperation
     *
     * @param info
     * @return
     *     returns int
     */
    @WebMethod(operationName = "TaskPathOperation")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "TaskPathOperation", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.TaskPathOperation")
    @ResponseWrapper(localName = "TaskPathOperationResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.TaskPathOperationResponse")
    public int taskPathOperation(
            @WebParam(name = "info", targetNamespace = "")
                    TaskPathInfo info);

    /**
     * Service definition of function taskdata__DeadlineTaskOperation
     *
     * @param info
     * @return
     *     returns int
     */
    @WebMethod(operationName = "DeadlineTaskOperation")
    @WebResult(name = "Result", targetNamespace = "")
    @RequestWrapper(localName = "DeadlineTaskOperation", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.DeadlineTaskOperation")
    @ResponseWrapper(localName = "DeadlineTaskOperationResponse", targetNamespace = "http://tempuri.org/taskdata.xsd", className = "com.wgptwo.DeadlineTaskOperationResponse")
    public int deadlineTaskOperation(
            @WebParam(name = "info", targetNamespace = "")
                    DeadlineTaskInfo info);

}
